name: zim-furniture-store
services:
- name: backend
  source_dir: backend
  github:
    repo: ljirna/senior-design-project
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 80
  envs:
  - key: DB_NAME
    value: zim_furniture_store
  - key: DB_PORT
    value: "25060"
  - key: JWT_SECRET
    value: ${JWT_SECRET}

- name: frontend
  source_dir: frontend
  github:
    repo: ljirna/senior-design-project
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 80

databases:
- name: db
  engine: MYSQL
  version: "8"
  production: true
